### ISSUE TITLE
屏幕共享会导致闪退

### ISSUE THREAD

**Issue by LiAlH4qwq** [flathub/com.tencent.wemeet#39]
无论在x11或wayland下进行屏幕共享，都会弹出gnome wayland的截取屏幕对话框，选择确认后软件就会闪退，去除ld preload后恢复正常

**Comment by catsout** [comment]
可以安装下 com.tencent.wemeet.Debug
然后看下 coredump

**Comment by catsout** [comment]
@ztelliot

**Comment by catsout** [comment]
我这边 kde 没有问题，你有安装 xdg-desktop-portal 吗

**Comment by ztelliot** [comment]
我这边 gnome 在 x11 和 wayland 下也没问题，使用命令行启动应该能看到日志，麻烦贴一下？

```
flatpak run com.tencent.wemeet
```

**Comment by LiAlH4qwq** [comment]
@catsout @ztelliot
x11下运行：
lialh4@LiAlH4-Laptop ~> flatpak run com.tencent.wemeet
/app/extra/opt/wemeet/wemeetapp.sh: line 43: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8): No such file or directory
wemeet:WemeetSatrt
Failed to create variant from json2024-12-28 08:11:21|140026101463680|xnn.XNNHandleMonitor|xnnhandlemonitor.cpp:35||regist handle,type:0 handle:700844048
2024-12-28 08:11:21|140026101463680|xnn.XNNRTResource|xnnrtresource.cpp:20||the acc thread cnt is 0
2024-12-28 08:11:21|140026101463680|xnn.XNNContext|xnncontext.cpp:99||init xnn context succ
2024-12-28 08:11:21|140026101463680|XNNReg|xnnlayerreg.cpp:866||layer map inited
2024-12-28 08:11:21|140026101463680|xnn.XNNHandleMonitor|xnnhandlemonitor.cpp:35||regist handle,type:0 handle:700845248
2024-12-28 08:11:21|140026101463680|xnn.XNNRTResource|xnnrtresource.cpp:20||the acc thread cnt is 0
2024-12-28 08:11:21|140026101463680|xnn.XNNContext|xnncontext.cpp:99||init xnn context succ
2024-12-28 08:11:21|140026101463680|XNNReg|xnnlayerreg.cpp:866||layer map inited
2024-12-28 08:11:21|140026101463680|xnn.XNNHandleMonitor|xnnhandlemonitor.cpp:35||regist handle,type:0 handle:698993360
2024-12-28 08:11:21|140026101463680|xnn.XNNRTResource|xnnrtresource.cpp:20||the acc thread cnt is 0
2024-12-28 08:11:21|140026101463680|xnn.XNNContext|xnncontext.cpp:99||init xnn context succ
Call
MicButtonQTView::OnViewStatefulChanged():btn_title:选择音频
MicButtonQTView::OnViewStatefulChanged():btn_title:选择音频
MicButtonQTView::OnViewStatefulChanged():btn_title:选择音频
MicButtonQTView::OnViewStatefulChanged():btn_title:选择音频
MicButtonQTView::OnViewStatefulChanged():btn_title:选择音频
MicButtonQTView::OnViewStatefulChanged():btn_title:解除静音
[hook] payload thread started
[payload x11 sanitizer] picked window 0x1400069 after 0 ms.
[hook] stream node_id: 95
[hook] portal status: running
[hook SYNC] pipewire_fd acquired: 184
[payload SYNC] pipewire_fd acquired: 184
[hook SYNC] pipewire screencast object allocated
[payload SYNC] got pipewire_handle.
[payload] pipewire thread started.
[payload SYNC] x11 sanitizer stopped.
[payload pw] stream state changed from unconnected to connecting
[payload pw] stream state changed from connecting to paused
[payload pw] param changed. received param type: Spa:Enum:ParamId:Latency
[payload pw] ignoring non-format param
[payload pw] param changed. received param type: Spa:Enum:ParamId:Format
[payload pw] spa_format_video_raw_parse retval: 4
[payload pw] actual params: width: 2880 | height: 1800 | framerate: 0.000000 | max_framerate: 90.006561 | format: BGRx | param_good: 1
[payload pw] stream state changed from paused to streaming
xdg-desktop-portal：
Information for package xdg-desktop-portal:
-------------------------------------------
Repository     : mirror-sle-update
Name           : xdg-desktop-portal
Version        : 1.18.2-150600.4.3.1
Arch           : x86_64
Vendor         : SUSE LLC <https://www.suse.com/>
Installed Size : 2.0 MiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : xdg-desktop-portal-1.18.2-150600.4.3.1.src
Upstream URL   : https://github.com/flatpak/xdg-desktop-portal
Summary        : A portal frontend service for Flatpak
Description    : 
    A portal frontend service for Flatpak and possibly other desktop containment frameworks.

    xdg-desktop-portal works by exposing a series of D-Bus interfaces known as portals under
    a well-known name (org.freedesktop.portal.Desktop) and object path
    (/org/freedesktop/portal/desktop).

    The portal interfaces include APIs for file access, opening URIs, printing and others.
系统信息：
lialh4@LiAlH4-Laptop ~ [127]> fastfetch
                 .-++:.                     lialh4@LiAlH4-Laptop
               ./oooooo/-                   --------------------
            `:oooooooooooo:.                OS: openSUSE Leap 15.6 x86_64
          -+oooooooooooooooo+-`             Host: 21CX (ThinkBook 14 G4+ IAP)
       ./oooooooooooooooooooooo/-           Kernel: 6.4.0-150600.23.30-default
      :oooooooooooooooooooooooooo:          Uptime: 2 days, 11 hours, 11 mins
    `  `-+oooooooooooooooooooo/-   `        Packages: 2202 (rpm), 44 (flatpak)
 `:oo/-   .:ooooooooooooooo+:`  `-+oo/.     Shell: fish 3.7.0
`/oooooo:.   -/oooooooooo/.   ./oooooo/.    Display (AUOC391): 2880x1800 @ 90Hz
  `:+ooooo+-`  `:+oooo+-   `:oooooo+:`      DE: Gnome 45.3
     .:oooooo/.   .::`   -+oooooo/.         WM: Mutter (X11)
        -/oooooo:.    ./oooooo+-            WM Theme: WhiteSur-Light-alt-pink
          `:+ooooo+-:+oooooo:`              Theme: WhiteSur-Light-alt-pink [GTK2/3/4]
             ./oooooooooo/.                 Icons: WhiteSur-pink-light [GTK2/3/4]
                -/oooo+:`                   Font: Noto Sans CJK SC (12pt) [GTK2/3/4]
                  `:/.                      Cursor: Adwaita (24px)
                                            Terminal: gnome-terminal 3.50.1
                                            Terminal Font: Monospace (12pt)
                                            CPU: 12th Gen Intel(R) Core(TM) i5-12500H (16) @ 4.5 GHz
                                            GPU: Intel Iris Xe Graphics
                                            Memory: 2.30 GiB / 15.35 GiB (15%)
                                            Disk (/): 384.78 GiB / 475.69 GiB (81%) - xfs
                                            Battery: 100% [Full]
                                            Locale: en_US.UTF-8

                                            ████████████████████████
                                            ████████████████████████

**Comment by catsout** [comment]
你可以试着自己编译 wemeet-wayland-screenshare
```
url: https://github.com/xuwd1/wemeet-wayland-screenshare.git
commit: a1c8cc5a015a275256eef672f7df70a1e78e4c78
```
然后下载 wemeet，在 host 环境下测试
如果还是闪退，就去 wemeet-wayland-screenshare 的 repo 提一下 issue

**Comment by ztelliot** [comment]
我在 Leap 15.6 上可以复现，flatpak 打包的会 crash，但 host 环境正常，尚不清楚问题在哪

<details>
<summary>gdb backtrace</summary>

```
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:220
#1  0x00007ffff7f9d28a in PipewireScreenCast::on_process(void*) () at /app/lib/wemeet/libhook.so
#2  0x00007ffff63af64d in call_process (impl=0x7fffa1c1cc30) at ../src/pipewire/stream.c:441
        _f = <optimized out>
#3  call_process (impl=0x7fffa1c1cc30) at ../src/pipewire/stream.c:434
        _f = <optimized out>
#4  impl_node_process_input (object=0x7fffa1c1cc30) at ../src/pipewire/stream.c:1022
        impl = 0x7fffa1c1cc30
        stream = 0x7fffa1c1cc30
        io = 0x7fffa1c204e0
        b = <optimized out>
#5  0x00007ffff63c1209 in process_node.isra.0 (data=data@entry=0x7fffa1c1f0d0, nsec=nsec@entry=7006223528126) at ../src/pipewire/impl-node.c:1469
        _f = <optimized out>
        _res = <optimized out>
        _n = <optimized out>
        this = <optimized out>
        p = <optimized out>
        a = 0x7fffefa77000
        data_system = <optimized out>
        status = <optimized out>
        was_awake = <optimized out>
        __func__ = {<optimized out> <repeats 13 times>}
#6  0x00007ffff6393422 in node_on_fd_events (source=<optimized out>) at ../src/pipewire/impl-node.c:1547
        cmd = 1
        nsec = 7006223528126
        data_system = 0x7fff4c1b6560
        this = 0x7fffa1c1f0d0
        __func__ = "node_on_fd_events"
#7  0x00007fffe609ca06 in loop_iterate (object=0x7fff4c25f348, timeout=<optimized out>) at ../spa/plugins/support/loop.c:612
        s = <optimized out>
        impl = 0x7fff4c25f348
        ep = {{events = 1, data = 0x7fffa1c1f700}, {events = 0, data = 0x0} <repeats 15 times>, {events = 4055886056, data = 0x7ffef1bfe8f8}, {events = 4055886080, data = 0x7ffff7fa116d <std::chrono::duration<long, std::ratio<1l, 1000l> > std::chrono::__duration_cast_impl<std::chrono::duration<long, std::ratio<1l, 1000l> >, std::ratio<1000l, 1l>, long, false, true>::__cast<long, std::ratio<1l, 1l> >(std::chrono::duration<long, std::ratio<1l, 1l> > const&)+45>}, {events = 0, data = 0x0}, {events = 4055886312, data = 0x0}, {events = 4055886112, data = 0x7ffff7fa1125 <std::enable_if<__is_duration<std::chrono::duration<long, std::ratio<1l, 1000l> > >::value, std::chrono::duration<long, std::ratio<1l, 1000l> > >::type std::chrono::duration_cast<std::chrono::duration<long, std::ratio<1l, 1000l> >, long, std::ratio<1l, 1l> >(std::chrono::duration<long, std::ratio<1l, 1l> > const&)+21>}, {events = 4055886312, data = 0x7ffef1bfe938}, {events = 4055886160, data = 0x7ffff7fa10fe <std::chrono::duration<long, std::ratio<1l, 1000l> >::duration<long, std::ratio<1l, 1l>, void>(std::chrono::duration<long, std::ratio<1l, 1l> > const&)+46>}, {events = 4055886192, data = 0x0}, {events = 4055886184, data = 0x7ffef1bfe978}, {events = 4055886208, data = 0x7ffff7f9ea1d <std::chrono::duration<long, std::ratio<1l, 1000000000l> > std::chrono::__duration_cast_impl<std::chrono::duration<long, std::ratio<1l, 1000000000l> >, std::ratio<1000000l, 1l>, long, false, true>::__cast<long, std::ratio<1l, 1000l> >(std::chrono::duration<long, std::ratio<1l, 1000l> > const&)+45>}, {events = 16, data = 0x7ffff5ee5cef <__GI___clock_nanosleep+111>}, {events = 4055886280, data = 0x7ffef1bfe9c8}, {events = 4055886240, data = 0x0}, {events = 4055886240, data = 0x50000ffff}, {events = 4055886304, data = 0x7ffff7f9bda0 <std::__atomic_base<pw_main_loop*>::operator pw_main_loop*() const+48>}, {events = 1277554576, data = 0x50000ffff}}
        e = <optimized out>
        i = 0
        nfds = 1
#8  0x00007ffff7fa4f60 in payload_start_pipewire_thread()::$_0::operator()() const () at /app/lib/wemeet/libhook.so
#9  0x00007ffff7fa4ec5 in void std::__invoke_impl<void, payload_start_pipewire_thread()::$_0>(std::__invoke_other, payload_start_pipewire_thread()::$_0&&) () at /app/lib/wemeet/libhook.so
#10 0x00007ffff7fa4e85 in std::__invoke_result<payload_start_pipewire_thread()::$_0>::type std::__invoke<payload_start_pipewire_thread()::$_0>(payload_start_pipewire_thread()::$_0&&) () at /app/lib/wemeet/libhook.so
#11 0x00007ffff7fa4e5d in decltype (std::__invoke((_S_declval<0ul>)())) std::thread::_Invoker<std::tuple<payload_start_pipewire_thread()::$_0> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) () at /app/lib/wemeet/libhook.so
#12 0x00007ffff7fa4e35 in std::thread::_Invoker<std::tuple<payload_start_pipewire_thread()::$_0> >::operator()() () at /app/lib/wemeet/libhook.so
#13 0x00007ffff7fa4d69 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<payload_start_pipewire_thread()::$_0> > >::_M_run() () at /app/lib/wemeet/libhook.so
#14 0x00007ffff60f69f4 in std::execute_native_thread_routine (__p=0x7fff880016e0) at ../../../../../libstdc++-v3/src/c++11/thread.cc:104
        __t = std::unique_ptr<std::thread::_State> = {get() = <optimized out>}
#15 0x00007ffff5e98e0e in start_thread (arg=<optimized out>) at pthread_create.c:447
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140732954310336, -729135146130081004, 140732954310336, -504, 0, 140733002519696, -729135146310436076, -728562937465013484}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#16 0x00007ffff5f1d7d4 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
```

</details>

**Comment by LiAlH4qwq** [comment]
leap16.0beta正常
